### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ITzOwen** [WorldCretornica/PlotMe-Core#248]
Hello, you probally know that I have been still having this problem, but I keep on having a "chunk error" also known as an Internal Server Error!
I have heard my config is edited wrong, and I do not know what for. Here are my configs:
[By the time you read it I will have plotme disabled, because I can not join]

PlotMe-DefaultGenerator:
http://imgur.com/iz9CWMe,yirjnY9#1

PlotMe-Core:
http://imgur.com/iz9CWMe,yirjnY9#0

Need the Console Issues? Here you go:
http://imgur.com/OsbXmN7,VcPSwG0#0
http://imgur.com/OsbXmN7,VcPSwG0#1

It would really help if you could say what to put in my config, and what I should do!

Thank you for your time!
:8ball: Owen :8ball:

**Comment by MattBDev** [comment]
I can't keep this issue open and like I said it isn't an actual bug so I don't want duplicate reports like this. It just keeps incrementing the issue counter....
Try adding this to your bukkit.yml:
`worlds:
    prisonplots:
        generator: PlotMe-DefaultGenerator`

**Comment by MattBDev** [comment]
I couldn't get indentation up there but you can see the proper format of what I said above on this website:
http://plotme.worldcretornica.com/setup.html

**Comment by ITzOwen** [comment]
Im still very lost :(

Could someone do a clear step by step for me?

**Comment by MattBDev** [comment]
I really can't get this any clearer. It is self explanatory. You need to add what the website says to your bukkit.yml file

**Comment by MattBDev** [comment]
Try watching this video: https://youtu.be/c74550Zlp84

**Comment by MattBDev** [comment]
@ITzOwen is your issue fixed? This ticket will be closed in 36 hours.

**Comment by enewearth** [comment]
Getting this exact same error. Basically the world generates like normal, but every once and a while a part of it will ungenerate, like a chunk error. If you walk into the error your get glitched out and cannot move or type any commands, then you get kicked for "Internal Server Error", if you try and rejoin you are automatically kicked for "Internal Server Error".

**Comment by MattBDev** [comment]
@enewearth what do you mean "the world generates like normal"? Do you mean it generates a normal minecraft world or it generates a plotworld?

**Comment by enewearth** [comment]
It generates a normal plotworld.

**Comment by enewearth** [comment]
Errors:
http://gyazo.com/b99d68b3a850dd77a5a4c65e125efa17
http://gyazo.com/ef8bd1593747253c87ba53aa09dd7168
http://gyazo.com/432ee63f94974bdf9e7b69062edab389

**Comment by MattBDev** [comment]
Those aren't errors, those are pictures of the chunks. An error is a message in the console telling you something went wrong. This looks a lot like a craftbukkit/spigot issue. Make sure you are running Minecraft 1.8 / 1.8.3

**Comment by enewearth** [comment]
I unistalled BarAPI and Bossmessage, and it seemed to be fixed. I thought it was a plotme issue because it only happened in the plotworld. Sorry about that.

**Comment by MattBDev** [comment]
@enewearth did you get any errors in the console when you had those installed? It might be helpful for me. \

**Comment by enewearth** [comment]
http://pastebin.com/514BjSDR

**Comment by MattBDev** [comment]
I am really not sure why it is interfering with that stuff but I am pretty sure I fixed it for the next version so I am going to close this ticket.

**Comment by ITzOwen** [comment]
It still happends.

I am doubting myself if I can upgrade to 1.8 because it might take away my
plugins!

**Comment by MattBDev** [comment]
@ITzOwen PlotMe 0.17 (the next version) will only support 1.8.3 so I suggest you update or I really can't help you.

**Comment by ITzOwen** [comment]
And the bukkit.yml does not work, it did not generate a world.

**Comment by MattBDev** [comment]
@ITzOwen I repeat: PlotMe 0.17 (the next version) will only support 1.8.3 so I suggest you update or I really can't help you.
If you submit another ticket about the same exact issue I will be forced to close it right away.

**Comment by ITzOwen** [comment]
I still have it. I might have to go into something I am doubting to do, but that is to pay you a bit too set it up on my server. It would be great for me, but I might have to do it.

**Comment by MarkusAV** [comment]
Really sorry that you're having a problem with PlotMe. It's not to hard to set up and the website should be more than enough help as well as the video tutorial.
However this might help: http://www.spigotmc.org/threads/plotme-official.37327/page-69#post-640484

**Comment by ITzOwen** [comment]
didnt help, still have it

**Comment by MattBDev** [comment]
ITzOwen. unless you upgrade to minecraft 1.8.3, we will not be able to help you any further.

**Comment by ITzOwen** [comment]
i did upgrade, i am now spigot 1.8.0 [1.8 & 1.7]

**Comment by MattBDev** [comment]
The version of spigot that supports both 1.7 and 1.8 is not the version you should be on. You should be running 1.8.3

**Comment by MattBDev** [comment]
I am locking this issue from further discussion. All discussion of internal server errors should be handled on the spigot forums.
