### ISSUE TITLE
Didn't works

### ISSUE THREAD

**Issue by YepImRobbie** [WorldCretornica/PlotMe-Core#311]
I did the conversion, it said converted.

Uploaded the new plotme and plotme default generator jars, and when I did plot info no plot was found, /p h didn't work /plot claim said internal error... So I just reuploaded a previous backup.

Sorry I have no error messages and I know it's likely to be something on my part but I'm too scared to do it right now, I'll try again in a few weeks time.

**Comment by MattBDev** [comment]
If there is no error messages I'm going to have to close this ticket. Let me know if you have more information to share

**Comment by benbristow** [comment]
Getting the same thing over here.

https://gist.github.com/benbristow/1e860a63ac143e9e7146

**Comment by jomo** [comment]
> ```Java
Caused by: java.lang.NullPointerException
        at com.worldcretornica.plotme_core.api.event.PlotEvent.<init>(PlotEvent.java:15) ~[?:?]
```

Looks like it can't [find the plot's world](https://github.com/WorldCretornica/PlotMe-Core/blob/10987d16eb24defb5cd7f42973fa50fbaab2a1ec/src/main/java/com/worldcretornica/plotme_core/api/event/PlotEvent.java#L15) for some reason.

**Comment by benbristow** [comment]
Done a restart..

https://gist.github.com/benbristow/632d5d3b6c2c7b4852ed

**Comment by MattBDev** [comment]
It was a dumb error on my end where I was passing null to the constructor. Fixed in 0.17.1

**Comment by YepImRobbie** [comment]
Glad I made a backup, still not willing to update, I'll leave it a good two weeks or so to reduce chance of error, thanks for being so quick at fixing this. :+1:
