### ISSUE TITLE
users can WorldEdit on plots that aren't theirs

### ISSUE THREAD

**Issue by coolty** [WorldCretornica/PlotMe-Core#81]
Users (non admins) can worldedit anywhere, not only on their own plots. BUT they can only seem to use the //repl tool, other worldedit commands only work on their own plot.

For example, if a user goes to someone else's plot (that they aren't added to) and does //repl 0, and then starts right clicking on blocks on that users plot, it will remove those blocks.
However, the wand only seems to work on their own plot or plots that they have been added to.

It's worth mentioning that I also have asyncworldedit installed, however I didn't have this problem until I upgraded my PlotMe to the .15 version.

Using spigot 1.8 builds

**Comment by MattBDev** [comment]
Make sure that you are using plotme version 0.15.2 because this issue has been solved in that build.

**Comment by coolty** [comment]
This isn't fixed, if a user is in gm 3 (spectate mode) they can still mess up other's plots with previous stated commands.

**Comment by EvilOlaf** [comment]
Can you provide a full startup log to find possible incompatibilities? It also would show us which versions of plugins you are using.

**Comment by coolty** [comment]
http://pastebin.com/raw.php?i=gAbJXZQ3

**Comment by coolty** [comment]
Hi,

Is there any update on this?

**Comment by MattBDev** [comment]
No update because I am not sure why you would give the gamemode command to players. Also spectator mode is a bit bugged in Spigot/Bukkit

**Comment by coolty** [comment]
I just tested it again without the use of gamemode, can still edit the roads/other plots that access isn't granted to. Even with latest version that supposedly fixed this issue.

**Comment by MattBDev** [comment]
No one but you is reporting this issue.Make sure you don't have the permissions to weanywhere or have that activated with the command.

**Comment by coolty** [comment]
http://wiki.sk89q.com/wiki/WorldEdit/Permissions 
I'm not seeing any permission "weanywhere" listed for worldedit. I think perhaps that was an old permission node that doesn't exist anymore?

**Comment by MattBDev** [comment]
This is in Plotme, not worldedit....

**Comment by coolty** [comment]
Oh, okay. No, no users have that permission node. I can set up a debug server if you would like to test it out yourself.

**Comment by coolty** [comment]
Besides, if they had the "weanywhere" permission node, they would be able to do other worldedit selection and editing to other plots/roads. It wouldn't be limited to just the replace tool.

**Comment by MattBDev** [comment]
Do you have "defaultweanywhere" set to true?

**Comment by coolty** [comment]
No, I don't. And like I said above if that was the case they would be able to literally use worldedit anywhere, not just the replace tool.

defaultWEAnywhere: false

**Comment by MattBDev** [comment]
I am testing this right now on a private server.

**Comment by coolty** [comment]
Okay, thank you for taking the time to test this.

**Comment by MattBDev** [comment]
After testing, I have not been able to reproduce this issue. Are you using plotme 0.15.2 and worldedit 6?

**Comment by coolty** [comment]
Yes, indeed I am. 

Here is a startup log of my server: http://pastebin.com/raw.php?i=gAbJXZQ3

I am using the latest build of WorldEdit 6 from their build server, and 0.15.2 of plotme.

**Comment by MattBDev** [comment]
I think this may be caused by AsyncWorldEdit. I am going to submit a patch to them to fix a possible incompatibility.

**Comment by coolty** [comment]
That's kinda what I figured, which is why I mentioned it just in case it was related to using that.

Thank you for your time, and please let me know via this thread when I should update.

**Comment by MattBDev** [comment]
There should be a config option in asyncworldedit that is called "plotMeFixEnabled". Set that to false.

**Comment by coolty** [comment]
I just tried that, same problem.

**Comment by MattBDev** [comment]
I would contact the developer of AsyncWorldEdit. Tell them I sent you to them because they are modifying PlotMe Classes and it is most likely causing these issues. If they complain about the PlotMe API, tell them it will get better in the next version but you need help now. (I got complaints about the api. You don't need to say anything about that really...)

**Comment by coolty** [comment]
Okay, I will do that. Thanks for your efforts in testing and narrowing down this issue!

**Comment by coolty** [comment]
here is the issue thread in case you want to watch it:
https://github.com/SBPrime/AsyncWorldEdit/issues/66
(and chime in with any information I may not know)

**Comment by SBPrime** [comment]
@MattBDev Could you elaborate more what did you mean by "modifying PlotMe Classes"? I only use your API to force mask update that's all. And what's the "possible incompatibility"?

**Comment by coolty** [comment]
Hi, I just tested this without AWE or AWE injector installed, and the issue still happens. So I am stumped once again...

**Comment by MattBDev** [comment]
@SBPrime When releasing PlotMe-Core I was afraid of whatever you did to patch the worldedit 6 bug would mess something up for users. I don't know if it would because I didn't look through enough of the code. I didn't realize that you added support for Plotme-Core, I haven't looked at your repo recently.

**Comment by MattBDev** [comment]
@coolty I think it is just you.

**Comment by SBPrime** [comment]
@MattBDev All I did was to force mask recalculation before each WE command thats all. This is not a WE 6 bug you can experience it on all versions. If you are refering to the mask class change I did nothing to add commpatibility for old versions.
